### ISSUE TITLE
Gallery can only be opened once

### ISSUE THREAD

**Issue by RadLikeWhoa** [daniellienert/DL.Gallery#10]
I'm including DL.Gallery on a Neos 3.0.2 site and I've run into the issue that I can only open galleries once.

1. Include a gallery on a site (selecting a tag, Bootstrap theme)
2. In the frontend, click a thumbnail
3. Close lightbox

The lightbox then disappears only visibly, however, it is still present in the DOM and overlays the grid of thumbnails, thus not allowing users to click any of the thumbnails.

The issue only occurs with the Bootstrap theme. The other theme is not affected. Currently, the only way to solve the issue is reloading the page.

**Comment by daniellienert** [comment]
Hey @RadLikeWhoa, 
thanks for reporting that issue. I also had the same problem, but forgot to fix it. Should be done by now. Please check if the latest version also fixes the issue for you.

**Comment by RadLikeWhoa** [comment]
Thanks, looks all good now.
