### ISSUE TITLE
Photoswipe not working

### ISSUE THREAD

**Issue by claudio-walser** [daniellienert/DL.Gallery#23]
Hi Daniel

Love your plugin, but i got an issue with Version 4.0.0 and Neos 5.0.4
The needed markup for photoswipe is not rendered which result in a js error. No pswp Elements are in the dom. As soon as i add those elements manuall at the end of
https://github.com/daniellienert/DL.Gallery/blob/master/Resources/Private/Fusion/Themes/BootstrapLightbox/BootstrapLightbox.html
or
https://github.com/daniellienert/DL.Gallery/blob/master/Resources/Private/Fusion/Themes/Justified/Justified.html
Everything works as expected. 
I am using your default Settings.yaml where Photoswipe is activated.

Not sure if i miss anything or if this is a bug with the recent version.

Anyway, thank you for your nice plugin, it seriously rocks!

Regards, Claudio

**Comment by daniellienert** [comment]
Hey Claudio, 
I already updated a project to Neos 5.0 / gallery 4.0 and didn't encounter any problem. A second is ongoing. I check that one today.

**Comment by daniellienert** [comment]
Hey Claudio, would you please check if https://github.com/daniellienert/DL.Gallery/pull/24 fixes your problem?

**Comment by claudio-walser** [comment]
Hi Daniel, sure i'll test this today evening.
Thank you very much

Kind regards

**Comment by claudio-walser** [comment]
Hey Daniel
This works like a charm, thank you for fixing things so fast.
