### ISSUE TITLE
Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by mberhorst** [daniellienert/DL.Gallery#28]
The JustifiedGallery.js throws this error: Cannot read property 'firstChild' of undefined

Used JustifiedGallery from this repository. It also doesn't matter which layout I choose. Bootstrap or justified, both throw this error when clicking an image.

**Comment by daniellienert** [comment]
Hey @mberhorst, the bug should be gone with the latest release: https://github.com/daniellienert/DL.Gallery/releases/tag/4.2.0

Please check if it works for you now.

**Comment by mberhorst** [comment]
Works like a charm. Many thanks @daniellienert
